[project]
name = "ejemplo-django-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.4",
    "ipython>=8.37.0",
    "pillow>=11.3.0",
]
