# Generated by Django 5.2.4 on 2025-08-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_noticia_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
    ]
